### ISSUE TITLE
[bug] Некорректный результат процессинга предиката

### ISSUE THREAD

**Issue by InRedikaWB** [itmo-mpa/mpa-backend#104]
Конфирм стабильный. Репродьюс:
1. Создать пациента
2. Не добавлять никакие данные
3. Перейти HS1 => HS2 => HS4
4. Убедиться в том, что переход HS4 => HS5 рекомендуется, хотя для него недостаточно информации.

![image](https://user-images.githubusercontent.com/22368203/58664736-ef230380-8337-11e9-9bb4-e37a73af716f.png)

**Comment by AntipovAndrey** [comment]
Баг не на бэкенде. Если есть переход, значит в бд лежит предикат не зависящий от контекста пациента.
