### ISSUE TITLE
Travis не может установить JDK в текущей конфигурации

### ISSUE THREAD

**Issue by Arthasasyan** [itmo-mpa/mpa-backend#110]
В #109 появились проблемы с тем, что Travis больше не может установить `oraclejdk`
Судя по [информации](https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365) от поддержки Travis, это связано с тем, что дефолтный `dist` теперь по умолчанию `xenial`, а не `trusty`
Решением может быть принудительное выставление `trusty` или использование `openjdk`

**Comment by Rizzen** [comment]
Закрыто в https://github.com/itmo-mpa/mpa-backend/pull/111
