### ISSUE TITLE
Минимальный API драфтов статуса

### ISSUE THREAD

**Issue by AntipovAndrey** [itmo-mpa/mpa-backend#13]
Добавить API для драфтов статуса:
```get /patient/id/status/draft``` - получение текущего черновика статуса 
```put /patient/id/status/draft``` - обновление черновика статуса 
```post /patient/id/status/draft``` - делает две вещи: 
1. Черновик становится текущим статусом пользователя, получает свой id. Этот id и вернуть на выходе (решить как - в виде json, или в хедере с http кодом 201 (created) 
2.  тут позже
Спросить у Влада какие данные мы принимаем на эдпоинты. 

PUT - пишет драфт 
POST - коммитит его, делает статусом

**Comment by AntipovAndrey** [comment]
по п.2, Влад:   
 " Создаёт новый черновик. Поля в этом черновике выбираются, исходя из нового стэйта (если он поменялся), а назначенные лекарства просто копируются"

**Comment by OrangeMemes** [comment]
По поводу данных. get и post отправляются без тела, с единственным параметром - id пациента - в пути. put принимает на вход тот же JSON, который описывает статус, исключая время создания (время создания вообще в черновиках нигде не фигурирует, это штука чисто для настоящих статусов).

Из важного: статус обязательно включает в себя айдишник стэйта и список назначенных лекарств.

**Comment by Steyrix** [comment]
Мы с Иваном Зеленковым взяли бы эту задачу

**Comment by AntipovAndrey** [comment]
отдельным таском пойдет доработка по новым требованием
