### ISSUE TITLE
Создать метод POST /patients

### ISSUE THREAD

**Issue by OrangeMemes** [itmo-mpa/mpa-backend#25]
На вход принимаем JSON следующего формата:
`{
  "name": "Иван Антонов",
  "age": 20,
  "diseaseId": 1
}`
Вызываем в базе процедуру создания пользователя, у которой такая сигнатура: `create_patient(IN name VARCHAR(50), IN age INT, IN diseaseId INT, OUT statusCode INT, OUT errorMessage VARCHAR(100), OUT patientId INT)`

Если statusCode==0, то отдаём на фронт код 200 (если очень хотите, можем договориться на 201, но выглядит избыточно) и результат в формате `{"patientId": 1}`. Иначе отдаём код 500 и описание ошибки в формате `{"errorMessage": "Такая болезнь не существует"}

**Comment by OrangeMemes** [comment]
Я пытался вставить красивый JSON, но не смог совладать с маркдауном. Надо было юзать джиру.

**Comment by AntipovAndrey** [comment]
Хранить процедуру мы не будем.
Делать ишую после #26

**Comment by AntipovAndrey** [comment]
Модель выглядит сейчас так
![image](https://user-images.githubusercontent.com/23316154/56097836-19dd0800-5f02-11e9-8cee-9aefd563e314.png)

то, что вместо age - дата, это поменялись требования
