### ISSUE TITLE
Создать метод GET /diseases

### ISSUE THREAD

**Issue by OrangeMemes** [itmo-mpa/mpa-backend#26]
Берём все записи из таблицы diseases и возвращаем на фронт в формате:
`[
  {
    "id": 1,
    "name": "Астма"
  }, {
    "id": 2,
    "name": "Аритмия"
  }
]`
Значения полей id и name берутся из полей id и name соответственно.

**Comment by AntipovAndrey** [comment]
Думаю еще и POST сюда же

**Comment by dmrsmglov** [comment]
Окк
