### ISSUE TITLE
Создать метод GET /patients

### ISSUE THREAD

**Issue by OrangeMemes** [itmo-mpa/mpa-backend#27]
Вернуть все строки таблицы patients_list в виде JSON-массива:
`[
  {
    "id": 1,
    "name": "Екатерина Меттус",
    "age": 20,
    "diseaseName": "Астма"
  }
]`
Все поля объекта тянутся из одноименных полей таблицы.

**Comment by AntipovAndrey** [comment]
Сейчас ответ в таком формате:
![image](https://user-images.githubusercontent.com/23316154/56097750-2b71e000-5f01-11e9-8104-bebb6084d3b5.png)

статуса в ишуе нет, но мы оставляем.

надо добавить поле с названием заболевания в модель выше
и писать в нее имя из текущего ```disease``` в entity ```Patient```.
апи для создания болезни пока нет. так что добавляем сами в бд, лиюо пишем для себя spring boot runner (можете спросить если не понятно), который добавит пару болзней на старте
но не нало коммитить его
