### ISSUE TITLE
Создать метод GET /disease/{diseaseId}/medicine

### ISSUE THREAD

**Issue by OrangeMemes** [itmo-mpa/mpa-backend#28]
Селектит записи из таблицы medicine, фильтруя их по полю diseaseId.

Поддерживает опциональный строковый query-параметр search - для фильтрации по названию препарата или действующему веществу. Можно тупо дописать в WHERE условие вида LIKE или можно как-нибудь по-умному фильтровать и сортировать на стороне бэка -- это уже на вашей совести.

Формат ответа:
`[
  {
    "id": 1,
    "name": "Тералиджен",
    "activeSubstance": "Алимемазин"
  }
]`
Все поля тянутся из одноименных полей таблицы.

**Comment by AntipovAndrey** [comment]
#63
