### ISSUE TITLE
Реализация моделей лекарств

### ISSUE THREAD

**Issue by AntipovAndrey** [itmo-mpa/mpa-backend#38]
Реализовать модели на схеме ниже. 
Неконтрастным выделены готовые модели.

Типы данных:

| Схема       | Модель       | 
| ----------- |:-------------:|
| ID              |   Long         |
| Date          |   Instant      |
| Varchar     |   String        |

Если пишите на java - расставляйте над геттерами и параметрами сеттеров аннотации jetbrains ```@Nullable @Notnull ```

![image](https://user-images.githubusercontent.com/23316154/56145353-cf649580-5fac-11e9-8cf5-415ccfa00d5f.png)

**Comment by PABchik** [comment]
Добавил сущности с зависимостями. Получается костыль с prescriptions. По сути prescriptions - таблица для организации связи многие ко многим и ее стоило бы так и организовывать, но котлин ругается, если пытаюсь описать с помощью аннотаций эту связь. Поэтому в этом коммите d622d4f410de7cc4fc695f3e1edf9fc7f3ad3e1b добавил связь medicine и statuses через отдельную сущность prescriptions.

**Comment by AntipovAndrey** [comment]
@PABchik думаю отдельную таблицу и надо, так и DiseaseAttributeValue сделаны. 
Что с котлином было?
Там в аннотациях немного другой синтаксис, нежели в джаве

**Comment by PABchik** [comment]
в @JoinTable ругается, когда пытаюсь joinColumns, inverseJoinColumns присвоить значение @JoinColumn(). Видимо просто синтаксис другой. Я у себя оттестил, вроде бы все генерится как надо
