### ISSUE TITLE
Изменить формат предиката

### ISSUE THREAD

**Issue by AntipovAndrey** [itmo-mpa/mpa-backend#89]
Нужно поменять формат символьной ссылки с ```$foo.bar``` в ```{foo.bar}```
Нужно для создания триггера в бд с проверкой на валидность предиката.

**Comment by InRedikaWB** [comment]
Дак а мы это уже заапрувили? Выкатываем до понедельника? Если да, то нужно вносить изменения в уже добавленые предикаты.

**Comment by AntipovAndrey** [comment]
@InRedikaWB Влад сказал, что можно делать, если хватает времени. Предикаты в самой бд я заменю после деплоя
